source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Attendance' do
    pod 'PureLayout'
    pod 'FontAwesomeKit'
    pod 'IQKeyboardManager'
    pod 'STPopup'
    pod 'SwiftOverlays'
    pod 'DZNEmptyDataSet'
    pod 'SDWebImage'
    pod 'Alamofire'
    pod 'DropDown'
    pod 'INSPhotoGallery'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    pod 'Firebase/Messaging'
    pod 'OpenCV', '~> 2.4'
end
